### ISSUE TITLE
Support generating soci indexes for all or some platforms in a multi-arch Image

### ISSUE THREAD

**Issue by yob** [CloudSnorkel/standalone-soci-indexer#3]
Thanks for a great tool! soci indexes have made a big improvement to our task startup times, and this has been the easiest way for us to generate them in CI where containerd isn't available.

One gap we've noticed that would be super helpful would be to support creating soci indexes for multi-arch images. For example, we run the datadog agent in many tasks and the image that's pulled from docker hub looks like this:

![2024-03-20_22-55](https://github.com/CloudSnorkel/standalone-soci-indexer/assets/8132/f237cb4e-aa40-4658-abaa-f4ad3ade317d)

We reference it in task definitions via the tag that points to the image index (`dddddddddddd.dkr.ecr.us-east-1.amazonaws.com/ecr-public/datadog/agent:7.49.0`). The four sub-images are different platforms (linux amd64, linux arm64, etc), and fargate pulls just the one it needs.

However, when we try to generate the soci index we get an error:

```
./standalone-soci-indexer dddddddddddd.dkr.ecr.us-east-1.amazonaws.com/ecr-public/datadog/agent:7.49.0
{"level":"info","time":"2024-03-20T22:59:18+11:00","message":"Indexing and pushing ecr-public/datadog/agent:7.49.0 to dddddddddddd.dkr.ecr.us-east-1.amazonaws.com"}
{"level":"info","RegistryURL":"dddddddddddd.dkr.ecr.us-east-1.amazonaws.com","time":"2024-03-20T22:59:18+11:00","message":"Initializing registry client"}
{"level":"warn","RegistryURL":"dddddddddddd.dkr.ecr.us-east-1.amazonaws.com","time":"2024-03-20T22:59:20+11:00","message":"Image manifest validation error: Empty config media type."}
```

We can work around it by creating a tag that points directly to the image we want:

```
skopeo copy --all --preserve-digests \
  docker://dddddddddddd.dkr.ecr.us-east-1.amazonaws.com/ecr-public/datadog/agent@sha256:9a161b6fc2f8ef74bb368f56edcac33a91b494d082da3693a600751a1a68b7d8 \
  docker://dddddddddddd.dkr.ecr.us-east-1.amazonaws.com/ecr-public/datadog/agent:7.49.0-amd64
```

Then creating the soci index works:
```
./standalone-soci-indexer dddddddddddd.dkr.ecr.us-east-1.amazonaws.com/ecr-public/datadog/agent:7.49.0-amd64
```
Fargate tasks seem to use this soci index, which is great. It'd be helpful to have a way to generate the soci index without the tag shenanigans though.

**Comment by kichik** [comment]
Sorry for missing this. I didn't have a watch on the repo. I do now.

Is there an easy way I can get one of those multi-arch Datadog images into my ECR for testing?

Alternatively, PRs would be welcome for this.

**Comment by yob** [comment]
The easiest way is probably to setup ECR with a pull through cache for the ECR public gallery:

![2024-04-23_22-11](https://github.com/CloudSnorkel/standalone-soci-indexer/assets/8132/3aa2afed-f2a2-46fa-8abb-150fd07bbb41)

Assuming you choose a repository prefix of `ecr-public`, it should be possible to populate the registry with a datadog image by doing:

```
docker pull dddddddddddd.dkr.ecr.<region>.amazonaws.com/ecr-public/datadog/agent:7.49.0
```
This should pull the image from https://gallery.ecr.aws/datadog/agent

**Comment by yob** [comment]
brilliant, thanks! We'll test out 1.0.2 and let you know how it goes

**Comment by yob** [comment]
Confirmed: we were able to point `standalone-soci-indexer` v1.0.2 at the image manifest, and it generated soci indexed for all the images in a loop ❤️

**Comment by kichik** [comment]
Awesome! I'm glad to hear it worked.

For future reference, I used this command to get a testable image:

```
docker run quay.io/skopeo/stable copy --all docker://public.ecr.aws/datadog/agent:7.49.0 docker://1234567890.dkr.ecr.us-east-1.amazonaws.com/soci-test:latest --dest-creds ...
```
