### ISSUE TITLE
Uploaded indexes missing an ImageIndex

### ISSUE THREAD

**Issue by yob** [CloudSnorkel/standalone-soci-indexer#5]
On April 25th I used v1.0.2 to build soci indexes for our mirrored datadog image. We got a soci index for each of the four images, plus in Image Index with a label matching the sha256 of the indexed image:

![ecr-with-soci-1ea5950e61fc1cc2667a5f7facb6eeec](https://github.com/user-attachments/assets/358ed091-c74b-4ddd-b817-948d7e8d8fdc)

Today I used v1.0.2 with the same command and I get soci indexes pushed back to ECR but no Image Index labels with the sha256:

![2024-07-25_13-00](https://github.com/user-attachments/assets/7c4ff25a-9bac-4c56-8d40-b8e1e17b0189)

My understanding is the sha256 labeled image indexes are required for fargate to find and use the index. It seems weird that v1.0.2 worked in April and not now. Is it possible something changed on ECR side to prevent that extra push working? I can't see any errors or warnings in the soci-standalone-indexer log though :thinking:

**Comment by yob** [comment]
oh interesting, 80fb4f8fac53c9c69283eadbf12107d88e8ac216 looks like it was trying to address the same symptoms?

**Comment by kichik** [comment]
I can confirm I see the same. Even updating all dependencies to the latest version doesn't help. Worse yet, the [original Lambda function](https://github.com/aws-ia/cfn-ecr-aws-soci-index-builder/) that this is based on and was created by AWS also behaves the same.

@ollypom any idea what might have changed?

**Comment by ollypom** [comment]
Hey folks, this behavior is completely expected. [Amazon ECR announced support](https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-ecr-oci-image-distribution-version-1-1/) for the [OCI 1.1 Image and Distribution specs](https://opencontainers.org/posts/blog/2024-03-13-image-and-distribution-1-1/) back at the end of June. When that launch happened, the SOCI client detects that it is 1.1 supported registry and will not push an ImageIndex. 

With OCI 1.1 we can use the new [Referrers API](https://github.com/opencontainers/distribution-spec/blob/v1.1.0/spec.md#listing-referrers) to see which SOCI Indexes (and SBOMs, Signatures etc) are attached to a Container Image. The ImageIndex was a workaround to see associated Indices until the Referrers API was available. The SOCI client will fail back to the ImageIndex approach if the Registry you are pushing to does not support OCI 1.1.

A few weeks ago I updated the [SOCI Workshop](https://catalog.workshops.aws/seekableoci/en-US/2-soci-indexes/storing#finding-the-index-in-a-repository) to discuss this new behavior, and has an example of using `curl` to query the Referrers API and show related artifacts to an Image.

```bash
curl \
    --silent \
    --user AWS:$ECR_PASSWORD \
    https://$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/v2/nginx-demo/referrers/$IMAGE_DIGEST?artifactType=application%2Fvnd.amazon.soci.index.v1%2Bjson | jq -r '.'

{
  "manifests": [
    {
      "digest": "sha256:622e58b8e72deb97c87fe8aa7da7ac23612ef215435aea86d053a44349badc19",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "artifactType": "application/vnd.amazon.soci.index.v1+json",
      "size": 1291,
      "annotations": {
        "com.amazon.soci.build-tool-identifier": "AWS SOCI CLI v0.1"
      }
    }
  ],
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2
}
```


The take away, nothing is broken, and the your Images (with a SOCI Index attached) should still be lazy loaded on Fargate 😄

**Comment by yob** [comment]
ah! I had no idea that was a thing, thankls for the detailed and patient explaination :heart: 

Armed with that context and the right words, now I notice that when I click on a particular image in ECR I can see the soci index referenced and "referrers":

![2024-07-26_22-26](https://github.com/user-attachments/assets/8178bbca-cc0a-4a53-a789-412b7ca52810)

**Comment by kichik** [comment]
Thanks @ollypom! I can confirm I see that too and using those images does print `"soci"` for the following command:

```
curl -s ${ECS_CONTAINER_METADATA_URI_V4}/task | jq .Containers[].Snapshotter
```
